cmake_minimum_required(VERSION 3.5.1)
project(WindowsSample)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O2 -Wall -DNDEBUG")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:CONSOLE")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /ENTRY:mainCRTStartup")

add_compile_options(/W4 /wd4710)

set(OUTPUT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../PrecompiledSamples/NYX320_Samples")
if(EXISTS "${OUTPUT_PATH}")
    file(REMOVE_RECURSE "${OUTPUT_PATH}")
    message(STATUS "Deleted existing directory: ${OUTPUT_PATH}")
endif()

file(MAKE_DIRECTORY ${OUTPUT_PATH}) 
message(STATUS "Created directory: ${OUTPUT_PATH}")

set(CMAKE_CONFIGURATION_TYPES "Release" CACHE STRING "" FORCE)

include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../Include")
string(TOLOWER "${CMAKE_GENERATOR_PLATFORM}" generator_platform_lower)
message(STATUS "CMAKE_GENERATOR_PLATFORM ${CMAKE_GENERATOR_PLATFORM}")
if(generator_platform_lower MATCHES "x64|win64")
message(STATUS "Building for x64")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}/x64")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
link_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../Lib/x64")
set(CMAKE_MSVCIDE_RUN_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../Bin/x64")
elseif(generator_platform_lower MATCHES "x86|win32")
message(STATUS "Building for x86")
message(FATAL_ERROR "not support x86 anymore")
endif()

add_subdirectory(ColorResolutionChange)
add_subdirectory(ColorExposureTimeSetGet)
add_subdirectory(DevHotPlugCallbackC)
add_subdirectory(DevHotPlugCallbackCpp)
add_subdirectory(DeviceConnectByIP)
add_subdirectory(DeviceConnectBySN)
add_subdirectory(DeviceHWTriggerMode)
add_subdirectory(DeviceImportParamInitFile)
add_subdirectory(DeviceInfoGet)
add_subdirectory(DeviceIPAndSubnetMaskSet)
add_subdirectory(DeviceParamSetGet)
add_subdirectory(DeviceSearchAndConnect)
add_subdirectory(DeviceSetFrameRate)
add_subdirectory(DeviceSetNTP)
add_subdirectory(DeviceSetParamsByJson)
add_subdirectory(DeviceSetPTP)
add_subdirectory(DeviceSetSoftwareTriggerParameter)
add_subdirectory(DeviceStartStopStreaming)
add_subdirectory(DeviceSWTriggerMode)
add_subdirectory(DeviceUpgradeFirmWare)
add_subdirectory(FrameCaptureAndSave)
add_subdirectory(IRGMMCorrectionSetGet)
add_subdirectory(MultiConnection)
add_subdirectory(MultiConnectionInMultiThread)
add_subdirectory(PointCloudCaptureAndSave)
add_subdirectory(PointCloudCaptureAndSaveDepthImgToColorSensor)
add_subdirectory(PointCloudVectorAndSave)
add_subdirectory(PointCloudVectorAndSaveDepthImgToColorSensor)
add_subdirectory(SingleFrameDelayTest)
add_subdirectory(ToFExposureTimeOfHDRSetGet)
add_subdirectory(ToFExposureTimeOfWDRSetGet)
add_subdirectory(ToFExposureTimeSetGet)
add_subdirectory(ToFFiltersSetGet)
add_subdirectory(ToFResolutionChange)
add_subdirectory(TransformColorImgToDepthSensorFrame)
add_subdirectory(TransformDepthImgToColorSensorFrame)
