cmake_minimum_required(VERSION 3.5.1)
project(FrameViewer)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
add_compile_options(/W2 /wd4710 /wd4996 /wd4244 /wd4100)
string(TOLOWER "${CMAKE_GENERATOR_PLATFORM}" generator_platform_lower)
if(generator_platform_lower MATCHES "x64|amd64")
    message(STATUS "Building for x64")
    
    set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O2 -Wall -DNDEBUG")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:CONSOLE")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /ENTRY:mainCRTStartup")
    add_compile_options(/W4)
    set(CMAKE_CONFIGURATION_TYPES "Release" CACHE STRING "" FORCE)
    set(OUTPUT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../PrecompiledSamples/DS86_OpenCVSample")
    if(NOT(EXISTS "${OUTPUT_PATH}" AND IS_DIRECTORY "${OUTPUT_PATH}"))
        file(MAKE_DIRECTORY ${OUTPUT_PATH}) 
    endif()
    include_directories("../../../Include" "../Thirdparty/opencv-3.4.16/include")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    link_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../Lib/x64" "${CMAKE_CURRENT_SOURCE_DIR}/../Thirdparty/opencv-3.4.16/x64/vc15/lib")
    set(CMAKE_MSVCIDE_RUN_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../Bin/x64")
    add_executable(${PROJECT_NAME} "FrameViewer.cpp")
    target_link_libraries(${PROJECT_NAME} Scepter_api opencv_world3416)
else()
    message(FATAL_ERROR "not support x86 anymore")
endif()
