cmake_minimum_required(VERSION 3.5.1)
project(NYX320_OpenCVSample)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../Include" "${CMAKE_CURRENT_SOURCE_DIR}/../Thirdparty/opencv-3.4.16/include")
link_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../Lib/" "${CMAKE_CURRENT_SOURCE_DIR}/../Thirdparty/opencv-3.4.16/lib")

set(OUTPUT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../PrecompiledSamples")
if(NOT(EXISTS "${OUTPUT_PATH}" AND IS_DIRECTORY "${OUTPUT_PATH}"))
    file(MAKE_DIRECTORY ${OUTPUT_PATH}) 
endif()
set(EXECUTABLE_OUTPUT_PATH "${OUTPUT_PATH}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath,\$ORIGIN -Wl,-rpath,\$ORIGIN/../Lib -Wl,-rpath,\$ORIGIN/../Samples/OpenCV/Thirdparty/opencv-3.4.16/lib")
add_executable(${PROJECT_NAME} "FrameViewer.cpp")
target_link_libraries(${PROJECT_NAME} Scepter_api opencv_world)
